version: "3"
services:
    spree:
        build: .
        ports:
            - 3001:3001
        depends_on:
            - redis
            - postgres
            - memcached
            - elasticsearch
        environment:
            - REDIS_URL=redis://redis:6379
            - ES_URL2=http://elasticsearch:9200
            - DATABASE_URL=postgresql://danny:changeme@postgres:5432/fame_website_development
            - MEMCACHE_SERVERS=memcached

    webclient:
        build: ../fame-wc/.
        ports:
            - 3002:3002
        environment:
            - FAME_API_URL_US=http://spree:3001

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
        environment:
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
            - xpack.security.enabled=false
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
        ports:
            - 19200:9200
            - 19300:9300
    redis:
        image: redis:4.0-alpine
        ports:
            - "6379:6379"

    memcached:
        image: memcached:1.5-alpine
        ports:
            - "11211:11211"
        command: memcached -m 64

    postgres:
        image: postgres:9.4.19
        environment:
            - POSTGRES_USER=danny
            - POSTGRES_PASSWORD=changeme
        ports:
            - 5432:5432

volumes:
        elasticsearch-data:
            driver: local
