version: "3"
services:
    elasticsearch:  
        image: docker.elastic.co/elasticsearch/elasticsearch:5.6.9
        environment:
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
            - xpack.security.enabled=false
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
        ports:
            - 19200:9200
            - 19300:9300
    redis:
        image: redis:4.0-alpine
        ports:
            - "6379:6379"
    memcached:
        image: memcached:1.5-alpine
        ports:
            - "11211:11211"
        command: memcached -m 64
volumes:
        elasticsearch-data:
            driver: local