branch-defaults:
  elb-deploy:
    environment: development2
environment-defaults:
  development:
    branch: null
    repository: null
global:
  application_name: fameosity
  default_ec2_keyname: thanhops
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Passenger with Ruby
    2.3 running on 64bit Amazon Linux/2.4.3
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
