require 'overrides/spree_auth_devise/user_passwords_controller'
require 'overrides/spree_auth_devise/user_registrations_controller'
require 'overrides/spree_auth_devise/user_sessions_controller'
require 'overrides/spree_social/user_decorator'
require 'overrides/spree/product'
require 'overrides/devise/rails/routes'
require 'overrides/omniauth/strategy'
