Deface::Override.all[:"spree/user_registrations/new"].delete('add_socials_to_login_extras')
Deface::Override.all[:"spree/user_registrations/new"].delete('remove_new_customer_if_sessionomniauth')
Deface::Override.all[:"spree/user_sessions/new"].delete('add_socials_to_login_extras')
Deface::Override.all[:"spree/checkout/registration"].delete('auth_user_login_form')
Deface::Override.all[:"spree/checkout/_payment"].delete('promo_coupon_code_field')
