source 'http://rubygems.org'

gem 'rails', :github => 'rails/rails', :branch => '3-2-stable'

gem 'sprockets', '~> 2.0'
gem 'spree', :github => 'spree/spree', :branch => '1-3-stable'

# Provides basic authentication functionality for testing parts of your engine
gem 'spree_auth_devise', :git => "git://github.com/spree/spree_auth_devise", :branch => "1-3-stable"

gem 'mastercard_masterpass_api'
gem 'mastercard_api'
gem 'mumboe-soap4r'

gemspec
