<%= ENV[‘RAILS_ENV’] %>:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DBNAME'] %>
  pool: 10
  reconnect: true
  connect_timeout: 2
  username: <%= ENV['DBUSER'] %>
  password: <%= ENV['DBPASSWORD'] %>
  host: <%= ENV['DBHOST'] %>
