sandbox_data: &sandbox_data
  iec_id: '23'
  iec_key: '6b72rxHuJuN8WgHMMsNR'
  iec_url: '//iec-staging.3dc.com.au/'
  enabled: true

development:
  <<: *sandbox_data
test:
  <<: *sandbox_data
staging:
  <<: *sandbox_data
production:
  enabled: true
