---
production:
  hosts:
    10.81.192.84:6379
preproduction:
  hosts:
    localhost:6379
staging:
  hosts:
    localhost:6379
development:
  hosts:
    localhost:6379
test:
  hosts:
    localhost:6379
