class UniqueDiscountsPerItemOnSale < ActiveRecord::Migration
  def up
    execute(delete_all_but_latest)
    add_index(:discounts,
              [:discountable_type, :discountable_id, :sale_id],
              unique: true, name: short_index_name)
  end

  def down
    remove_index(:discounts, name: short_index_name)
  end

  private def delete_all_but_latest
    <<-SQL
    delete
      from discounts d using discounts d2
      where d.discountable_type = d2.discountable_type
        and d.discountable_id   = d2.discountable_id
        and d.sale_id           = d2.sale_id
        and d.created_at        < d2.created_at;
    SQL
  end

  # Autogenerated name is > database char limit.
  private def short_index_name
    :index_discounts_on_discountable_and_sale_id
  end
end
