scss_files: 'app/assets/stylesheets/**/*.css.scss'

linters:
  BorderZero:
    enabled: false

  Comment:
    enabled: false

  IdSelector:
    enabled: false

  Indentation:
    severity: warning
    character: space
    width: 2

  NestingDepth:
    max_depth: 3

  PlaceholderInExtend:
    enabled: false

  SelectorFormat:
    convention: hyphenated_BEM

  StringQuotes:
    style: single_quotes

  PropertySortOrder:
    enabled: false

  ColorVariable:
    enabled: false
