source "https://rubygems.org"

# Declare your gem's dependencies in wedding-atelier.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# jquery-rails is used by the dummy application
gem "jquery-rails"
gem 'spree', :github => 'spree/spree', :branch => '1-3-stable'
# Provides basic authentication functionality for testing parts of your engine
gem 'spree_auth_devise', git: 'git://github.com/spree/spree_auth_devise', branch: '1-3-stable'

group :test do
   gem 'factory_girl_rails', '4.2.1'
   gem 'rspec-rails', '~> 3.2'
   gem 'pg'
   gem 'test-unit', '~> 3.0'
end

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use debugger
# gem 'debugger'
